

require(pacman)
p_load(expss)

### Las etiquetas de los nombres de las variables y de los códigos de las mismas fueron cargadas 
## con el paquete "expss". Este presenta algunas ventajas para trabajar tanto con los códigos 
## obteniendo las salidas con etiquetas. 

###Para más información sobre el paquete: https://github.com/gdemin/expss


### Reemplazar "base_hogar" por el nombre del objeto en don

base_hogar = apply_labels(base_hogar,
                          CODUSU = 'Código para distinguir VIVIENDAS, permite aparearlas con Hogares y Personas. Además permite hacer el seguimiento a través de los trimestres',
                          ANO4 = 'Año de relevamiento',
                          TRIMESTRE = 'Ventana de Observación',
                          TRIMESTRE = c("1er Trimestre" = 1,
                                        "2do Trimestre" = 2,
                                        "3er Trimestre" = 3,
                                        "4to Trimestre" = 4),
                          NRO_HOGAR = 'Código para distinguir HOGARES, permite aparearlos con Personas',
                          REALIZADA = 'Entrevista individual realizada',
                          REALIZADA = c("Si" = 1,
                                        "No." = 2),
                          REGION = 'Código de Región',
                          REGION = c("Gran Buenos Aires" = 1,
                                     "Noroeste" = 40,
                                     "Nordeste" = 41,
                                     "Cuyo" = 42,
                                     "Pampeana" = 43,
                                     "Patagónica." = 44),
                          MAS_500 = 'Aglomerados según tamaño',
                          AGLOMERADO = 'Código de Aglomerado',
                          AGLOMERADO = c("Gran La Plata" = 2,
                                         "Bahía Blanca - Cerri" = 3,
                                         "Gran Rosario" = 4,
                                         "Gran Santa Fé" = 5,
                                         "Gran Paraná" = 6,
                                         "Posadas" = 7,
                                         "Gran Resistencia" = 8,
                                         "Cdro. Rivadavia - R.Tilly" = 9,
                                         "Gran Mendoza" = 10,
                                         "Corrientes" = 12,
                                         "Gran Córdoba" = 13,
                                         "Concordia" = 14,
                                         "Formosa" = 15,
                                         "Neuquén - Plottier" = 17,
                                         "S. del Estero - La Banda" = 18,
                                         "Jujuy - Palpalá" = 19,
                                         "Río Gallegos" = 20,
                                         "Gran Catamarca" = 22,
                                         "Salta" = 23,
                                         "La Rioja" = 25,
                                         "San Luis - El Chorrillo" = 26,
                                         "Gran San Juan" = 27,
                                         "Gran Tucumán - T. Viejo" = 29,
                                         "Santa Rosa - Toay" = 30,
                                         "Ushuaia - Río Grande" = 31,
                                         "Ciudad de Buenos Aires" = 32,
                                         "Partidos del GBA" = 33,
                                         "Mar del Plata - Batán" = 34,
                                         "Río Cuarto" = 36,
                                         "San Nicolás - Villa Constitución" = 38,
                                         "Rawson - Trelew" = 91,
                                         "Viedma - Carmen de Patagones." = 93),
                          PONDERA = 'Ponderación',
                          IV1 = 'Tipo de vivienda',
                          IV1 = c("Casa" = 1,
                                  "Departamento" = 2,
                                  "Pieza de inquilinato" = 3,
                                  "Pieza en hotel/pensión" = 4,
                                  "Local no construido para habitación" = 5,
                                  "Otros. Especificar." = 6),
                          IV1_ESP = 'Otros (Especificar)',
                          IV2 = 'Cuántos ambientes/  habitaciones  tiene  la  vivienda en  total?  (sin  contar  baño/s,  cocina,  pasillo/s,lavadero, garage)',
                          IV3 = 'Los pisos interiores son principalmente de...',
                          IV3 = c("Mosaico/baldosa/madera/cerámica/alfombra" = 1,
                                  "Cemento/ladrillo fijo" = 2,
                                  "Ladrillo suelto/tierra" = 3,
                                  "Otros. Especificar." = 4),
                          IV3_ESP = 'Otros. Especificar',
                          IV4 = 'La cubierta exterior del techo es de....',
                          IV4 = c("Membrana/cubierta asfáltica" = 1,
                                  "Baldosa/losa sin cubierta" = 2,
                                  "Pizarra/teja" = 3,
                                  "Chapa de metal sin cubierta" = 4,
                                  "Chapa de fibrocemento/plástico" = 5,
                                  "Chapa de cartón" = 6,
                                  "Caña/tabla/paja con barro/paja sola" = 7,
                                  "N/S. Depto en propiedad horizontal." = 9),
                          IV5 = 'El techo tiene cielorraso/revestimiento interior?',
                          IV5 = c("Si" = 1,
                                  "No." = 2),
                          IV6 = 'Tiene agua...',
                          IV6 = c("Por cañería dentro de la vivienda" = 1,
                                  "Fuera de la vivienda pero dentro del terreno" = 2,
                                  "Fuera del terreno." = 3),
                          IV7 = 'El agua es de...',
                          IV7 = c("Red pública (agua corriente)" = 1,
                                  "Perforación con bomba a motor" = 2,
                                  "Perforación con bomba manual" = 3,
                                  "Otras fuentes." = 4),
                          IV7_ESP = 'Otras fuentes. Especificar',
                          IV8 = '¿Tiene baño/letrina?',
                          IV8 = c("Si" = 1,
                                  "No." = 2),
                          IV9 = 'El baño o letrina está...',
                          IV9 = c("Si" = 1,
                                  "No." = 2),
                          IV10 =	'El baño tiene...',
                          IV10 = c("Dentro de la vivienda" = 1,
                                   "Fuera de la vivienda pero dentro del terreno" = 2,
                                   "Fuera del terreno." = 3),
                          IV11 =	'El desague del baño es...',
                          IV11 = c("Inodoro  con  botón/  mochila/ cadena y  arrastre	de agua" = 1,
                                   "Inodoro sin botón/cadena y con arrastre de agua (a balde)" = 2,
                                   "Letrina (sin arrastre de agua)." = 3),
                          IV12_1 =	'La vivienda está ubicada cerca de basural/es(3 cuadras O menos)',
                          IV12_1 = c("Si" = 1,
                                     "No." = 2),
                          IV12_2 =	'La vivienda está ubicada en zona inundable (en los últimos 12 meses)',
                          IV12_2 = c("Si" = 1,
                                     "No." = 2),
                          IV12_3 =	'La vivienda está ubicada en villa de emergencia (por observación)',
                          IV12_3 = c("Si" = 1,
                                     "No." = 2),
                          II1 =		'Cuántos  ambientes/  habitaciones tiene este  hogar para su uso exclusivo?',
                          II2 =	'De esos, cuántos usan habitualmente para dormir?',
                          II3 =	'Utiliza alguno exclusivamente como lugar de Trabajo(paraconsultorio,estudio,taller, negocio, etc.).',
                          II3 = c("Si" = 1,
                                  "No." = 2),
                          II3_1 =	'Si utiliza alguno exclusivamente como lugar de	Trabajo ¿Cuántos?.',
                          II4_1 =	'Tiene además...	Cuarto de cocina.',
                          II4_1 = c("Si" = 1,
                                    "No." = 2),
                          II4_2 =	'Tiene además... Lavadero.',
                          II4_2 = c("Si" = 1,
                                    "No." = 2),
                          II4_3 = 'Tiene además... Garage.',
                          II4_3 = c("Si" = 1,
                                    "No." = 2),
                          II5 = 'De esos ...(los si de preg.4) usan alguno para dormir.',
                          II5 = c("Si" = 1,
                                  "No." = 2),
                          II5_1 = 'Si Utiliza alguno para dormir ¿Cuántos?.',
                          II6 = 'De esos ...(los si de preg.4) utiliza alguno de	estos exclusivamente como lugar	de trabajo (consultorio, estudio, taller, negocio, etc.).',
                          II6 = c("Si" = 1,
                                  "No." = 2),
                          II6_1 = 'Si utiliza alguno exclusivamente como lugar de	trabajo ¿Cuántos?',
                          II7 = 'Régimen de tenencia',
                          II7 = c("Propietario de la vivienda y el terreno" = 1,
                                  "Propietario de la vivienda solamente" = 2,
                                  "Inquilino/arrendatario de la vivienda" = 3,
                                  "Ocupante por pago de impuestos/expensas" = 4,
                                  "Ocupante en relación de dependencia" = 5,
                                  "Ocupante gratuito (con permiso)" = 6,
                                  "Ocupante de hecho (sin permiso)" = 7,
                                  "Está en sucesión?" = 8,
                                  "Otra situación (Especificar).." = 9),
                          II7_ESP = 'Otra situación (Especificar).',
                          II8 = 'Combustible utilizado para cocinar',
                          II8 = c("Gas de red" = 1,
                                  "Gas de tubo/garrafa" = 2,
                                  "Kerosene/ leña/ carbón" = 3,
                                  "Otro (Especificar)." = 4),
                          II8_ESP = 'Otro. Especificar.',
                          II9 = 'Baño (tenencia y uso).',
                          II9 = c ("Uso exclusivo del hogar" = 1,
                                   " Compartido  con  otro/s  hogar/es  de  la  misma	vivienda" = 2,
                                   "Compartido con otra/s vivienda/s" = 3,
                                   "No tiene baño." = 4),
                          V1 = '¿En los últimos tres meses	 las personas de este hogar han vivido... de lo que ganan en el trabajo?.',
                          V1 = c("Si" = 1,
                                 "No." = 2),
                          V2 = '¿En los últimos tres meses	 las personas de este hogar han vivido... de alguna jubilación o pensión?.',
                          V2 = c("Si" = 1,
                                 "No." = 2),
                          V21 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... Aguinaldo de	alguna	jubilación	o  pensión cobrada el mes anterior?',
                          V21 = c("Si" = 1,
                                  "No." = 2),
                          V22 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... Retroactivo de	alguna jubilación o pensión que cobró el mes anterior?',
                          V22 = c("Si" = 1,
                                  "No." = 2),
                          V3 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... indemnización por despido?',
                          V3 = c("Si" = 1,
                                 "No." = 2),
                          V4 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... seguro de desempleo?',
                          V14= c("Si" = 1,
                                 "No." = 2),
                          V5 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... desubsidio	oayuda	social(en	dinero) del gobierno, iglesias, etc.?',
                          V5 = c("Si" = 1,
                                 "No." = 2),
                          V6 =	'¿En los últimos tres meses	 las personas de este hogar han vivido con...  mercaderías,  ropa,  alimentos			del gobierno	iglesias, escuelas,	etc.?',
                          V6 = c("Si" = 1,
                                 "No." = 2),
                          V7 =	'¿En los últimos tres meses	 las personas de este hogar han vivido con... mercaderías, ropa, alimentos de familiares,	vecinos u otras personas que no viven en  este	hogar?		',
                          V7 = c("Si" = 1,
                                 "No." = 2),
                          V8 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... algún alquiler (por una vivienda, terreno,	oficina, etc.)de su propiedad?',
                          V8 = c("Si" = 1,
                                 "No." = 2),
                          V9 = '¿En los últimos tres meses	 las personas de este hogar han vivido de... ganancias de algún negocio enel que  no	trabajan?',
                          V9 = c("Si" = 1,
                                 "No." = 2),
                          V10 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... intereses o rentas por  plazos fijos/	inversiones?',
                          V10 = c("Si" = 1,
                                  "No." = 2),
                          V11 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... una beca de estudio?',
                          V11 = c("Si" = 1,
                                  "No." = 2),
                          V12 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... cuotas de alimentos o  ayuda  en  dinero  de	personas que no viven en el hogar?',
                          V12 = c("Si" = 1,
                                  "No." = 2),
                          V13 =	'¿En los últimos tres meses	 las personas de este hogar han vivido con... gastar lo que tenían ahorrado?',
                          V13 = c("Si" = 1,
                                  "No." = 2),
                          V14 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... pedir préstamos a familiares/amigos',
                          V14 = c("Si" = 1,
                                  "No." = 2),
                          V15 =	'¿En los últimos tres meses	 las personas de este hogar han vivido de... pedir préstamos a bancos, financieras, etc.?',
                          V15 = c("Si" = 1,
                                  "No." = 2),
                          V16 = '¿En los últimos tres meses	 las personas de este hogar han vivido de... Compran en  cuotas  o  al  fiado  con  tarjeta  de	crédito o libreta?',
                          V16 = c("Si" = 1,
                                  "No." = 2),
                          V17 =	'Han tenido que vender alguna de sus pertenencias?',
                          V17 = c("Si" = 1,
                                  "No." = 2),
                          V18 =		'Tuvieron otros  ingresos  en  efectivo  (limosnas,	juegos de azar, etc.)',
                          V18 = c("Si" = 1,
                                  "No." = 2),
                          V19_A =	'menores de  10  años  ayudan  con  algún  dinero		trabajando?',
                          V19_A = c("Si" = 1,
                                    "No." = 2),
                          V19_B =	'Menores de  10  años  ayudan  con  algún  dinero	pidiendo?',
                          V19_B = c("Si" = 1,
                                    "No." = 2),
                          IX_TOT =		'Cantidad de miembros del Hogar',
                          IX_MEN10 =		'Cantidad de miembros del Hogar menores de 10 años',
                          IX_MAYEQ10 =		'Cantidad de miembros del Hogar de 10 y más años',
                          ITF =		'MONTO DE INGRESO TOTAL FAMILIAR',
                          DECIFR =		'Nro de decil del ingreso total del hogar del TOTAL	EPH',
                          IDECIFR =		'Nro de decil del ingreso total del hogar del TOTAL	EPH',
                          RDECIFR = 	'Nro de	decil de  ingreso  total  del  hogar  de  la	REGION.',
                          GDECIFR = 	'Nro de	decil de  ingreso  total  del  hogar	del	Conjunto	de AGLOMERADOS DE 500 MIL	Y MAS	HABITANTES.',
                          PDECIFR = 	'Nro de	decil de  ingreso  total  del  hogar	del	Conjunto  de  AGLOMERADOS  DE  MENOS  DE  500  MIL	HABITANTES',
                          ADECIFR = 	'Nro  de  decil  de  ingreso  total  del  hogar  del	AGLOMERADO',
                          IPCF = 	'Monto de ingreso per cápita familiar(ver AnexoI)',
                          DECCFR = 	'Nro de	decil del  ingreso  per  cápita  familiar  del	TOTAL EPH',
                          IDECCFR = 	'Nro  de  decil  del  ingreso  per  cápita  familiar  del	INTERIOR',
                          RDECCFR = 	'Nro de	decil de  ingreso  per  cápita  familiar  de  la	REGION',
                          GDECCFR = 	'Nro  de  decil  de  ingreso  per  cápita  familiar  del	Conjunto	de AGLOMERADOS DE 500 MIL	Y MAS	HABITANTES',
                          PDECCFR = 	'Nro  de  decil  de  ingreso  per  cápita  familiar  del	Conjunto  de  AGLOMERADOS  DE  MENOS  DE  500  MIL	HABITANTES',
                          ADECCFR = 	'Nro  de  decil  de  ingreso  per  cápita  familiar  del	AGLOMERADO',
                          PONDIH = 'Ponderador  del  ingreso  total  familiar  y		del	ingreso per cápita familiar',
                          VII1_1 = 	'Realización de las tareas de la casa		- Número de componente del hogar',
                          VII1_1 = c("Servicio doméstico" = 96,
                                     "Otra persona que no vive en el hogar." = 97),
                          VII1_2 =		'Realización de las tareas de la casa - Número de componente del hogar',
                          VII1_2 = c("Servicio doméstico" = 96,
                                     "Otra persona que no vive en el hogar." = 97),
                          VII2_1 =		'Otras personas que ayudan en las tareas de la casa		- Número de componente del hogar',
                          VII2_1 = c("Servicio doméstico" = 96,
                                     "Otra persona que no vive en el hogar" = 97,
                                     "Ninguna." = 98),
                          VII2_2 =		'Otras personas que ayudan en las tareas de la casa	- Número de componente del hogar',
                          VII2_2 = c("Servicio doméstico" = 96,
                                     "Otra persona que no vive en el hogar" = 97,
                                     "Ninguna." = 98),
                          VII2_3 =		'Otras personas que ayudan en las tareas de la casa	- Número de componente del hogar',
                          VII2_3 = c("Servicio doméstico" = 96,
                                     "Otra persona que no vive en el hogar" = 97,
                                     "Ninguna." = 98),
                          VII2_4 =		'Otras personas que ayudan en las tareas de la casa - Número de componente del hogar',
                          VII2_4 = c("Servicio doméstico" = 96,
                                     "Otra persona que no vive en el hogar" = 97,
                                     "Ninguna." = 98))
