
require(pacman)
p_load(tidyverse, expss)

#source("subir a github la funcion para descargar bases EPH")

### ¿Cómo definir un objeto que aplique luego en todo el script?

base_individual = apply_labels(base_individual,
                               CODUSU = 'Código para distinguir VIVIENDAS, permite aparearlas con Hogares y Personas. Además permite hacer el seguimiento a través de los trimestres',
                               NRO_HOGAR = ' Código para distinguir HOGARES, permite aparearlos con Personas',
                               COMPONENTE = 'Número de componente: N° de orden que se asigna a las personas que conforman cada hogar de la vivienda',
                               COMPONENTE = c("Servicio Doméstico en hogares" = 51,
                                              "Pensionistas en hogares" = 71),
                               H15 = 'Entrevista individual realizada',
                               H15 = c("Si" = 1,
                                       "No" = 2),
                               ANO4 = 'Año de relevamiento',
                               TRIMESTRE = 'Ventana de Observación',
                               TRIMESTRE = c("1er Trimestre" = 1,
                                             "2do Trimestre" = 2,
                                             "3er Trimestre" = 3,
                                             "4to Trimestre" = 4),
                               REGION = 'Código de Región',
                               REGION = c("Gran Buenos Aires" = 01,
                                          "Noroeste" = 40,
                                          "Nordeste" = 41,
                                          "Cuyo" = 42,
                                          "Pampeana" = 43,
                                          "Patagónica"),
                               MAS_500 = 'Aglomerados según tamaño',
                               AGLOMERADO = 'Código de Aglomerado',
                               AGLOMERADO = c("Gran La Plata" = 2,
                                              "Bahía Blanca - Cerri" = 3,
                                              "Gran Rosario" = 4,
                                              "Gran Santa Fé" = 5,
                                              "Gran Paraná" = 6,
                                              "Posadas" = 7,
                                              "Gran Resistencia" = 8,
                                              "Cdro. Rivadavia - R.Tilly" = 9,
                                              "Gran Mendoza" = 10,
                                              "Corrientes" = 12,
                                              "Gran Córdoba" = 13,
                                              "Concordia" = 14,
                                              "Formosa" = 15,
                                              "Neuquén - Plottier" = 17,
                                              "S. del Estero - La Banda" = 18,
                                              "Jujuy - Palpalá" = 19,
                                              "Río Gallegos" = 20,
                                              "Gran Catamarca" = 22,
                                              "Salta" = 23,
                                              "La Rioja" = 25,
                                              "San Luis - El Chorrillo" = 26,
                                              "Gran San Juan" = 27,
                                              "Gran Tucumán - T. Viejo" = 29,
                                              "Santa Rosa - Toay" = 30,
                                              "Ushuaia - Río Grande" = 31,
                                              "Ciudad de Buenos Aires" = 32,
                                              "Partidos del GBA" = 33,
                                              "Mar del Plata - Batán" = 34,
                                              "Río Cuarto" = 36,
                                              "San Nicolás - Villa Constitución" = 38,
                                              "Rawson - Trelew" = 91,
                                              "Viedma - Carmen de Patagones." = 93),
                               PONDERA = 'Ponderación',
                               CH03 = 'Relación de parentesco',
                               CH03 = c("Jefe/a" = 1,
                                        "Cónyuge / Pareja" = 2,
                                        "Hijo/a Hijastro/a" = 3,
                                        "Yerno/Nuera" = 4,
                                        "Nietro/a" = 5,
                                        "Madre/Padre" = 6,
                                        "Suegro/a" = 7,
                                        "Hermano/a" = 8,
                                        "Otros Familiares" = 9,
                                        "No familiares" = 10),
                               CH04 = 'Sexo',
                               CH04 = c("Varón" = 1,
                                        "Mujer" = 2),
                               CH05 = 'Fecha de nacimiento (día, mes y año)',
                               CH06 = 'Edad en años cumplidos',
                               CH07 = '¿Actuamente está...',
                               CH07 = c("unido?" = 1,
                                        "casado?" = 2,
                                        "separado/a o divorsiado/a?" = 3,
                                        "viudo/a?" = 4,
                                        "soltero/a?" = 5,
                                        "Ns/Nr." = 9),
                               CH08 = 'Tipo de cobertura médica',
                               CH08 = c("Obra social (incluye PAMI)" = 1,
                                        "Mutual / Prepaga / Servicio de emergencia" = 2,
                                        "Planes y seguros Públicos" = 3,
                                        "No paga ni le descuentan" = 4,
                                        "Ns./Nr." = 9,
                                        "Obra social y Mutual / Prepaga / Servicio de Emergencia" = 12,
                                        "Obra social y Planes y Seguros Públicos" = 13,
                                        "Mutual / Prepaga / Servicio de Emergencia / Planes y Seguros Públicos" = 23,
                                        "Obra social, mutual / prepaga / servicio de emergencia y planes y seguros púbilcos" = 123),
                               CH09 = '¿Sabe leer y escribir?',
                               CH09 = c("Sí" = 1,
                                        "No" = 2,
                                        "Menor de 2 años." = 3),
                               CH10 = '¿Asiste o asistió a algún establecimiento educativo? (colegio, escuela, universidad)',
                               CH10 = c("Sí, asiste" = 1,
                                        "No asiste, pero asistió" = 2,
                                        "Nunca asistió" = 3,
                                        "Ns/Nr." = 9),
                               CH11 = 'Ese establecimiento es...',
                               CH11 = c("Público" = 1,
                                        "Privado" = 2,
                                        "Ns./Nr.." = 9),
                               CH12 = '¿Cuál es el nivel más alto que cursa o cursó?',
                               CH12 = c("Jardín / Preescolar" = 1,
                                        "Primario" = 2,
                                        "EGB" = 3,
                                        "Secundario" = 4,
                                        "Polimodal" = 5,
                                        "Terciario" = 6,
                                        "Universitario" = 7,
                                        "Posgrado Univ." = 8,
                                        "Educación especial (discapacitado)" = 9,
                                        "Ns/Nr." = 99),
                               CH13 = '¿Finalizó ese nivel?',
                               CH13 = c("Sí" = 1,
                                        "No" = 2,
                                        "Ns/Nr." = 9),
                                CH14 = '¿Cuál fue el último año que aprobó?',
                               CH14 = c("Ninguno" = 0,
                                        "Primero" = 1,
                                        "Segundo" = 2,
                                        "Tercero" = 3,
                                        "Cuarto" = 4,
                                        "Quinto" = 5,
                                        "Sexto" = 6,
                                        "Síptimo" = 7,
                                        "Octavo" = 8,
                                        "Noveno" = 9,
                                        "Educación especial" = 98,
                                        "Ns/Nr." = 99),
                               CH15 = '¿Dónde nació?',
                               CH15 = c("En esta localidad" = 1,
                                        "En otra localidad de esta provincia" = 2,
                                        "En otra provincia (especificar)" = 3,
                                        "En un país limitrofe (especificar Brasil, Bolivia, Chile, Paraguay, Uruguay)" = 4,
                                        "En otro país (especificar)" = 5,
                                        "Ns./Nr.." = 9),
                               CH15_COD = 'Especificar',
                               CH15_COD = c("En otra provincia" = 3,
                                            "En un paìs limítrofe" = 4,
                                            "En otro país." = 5),
                               CH16 = '¿Dónde vivía hace 5 años?',
                               CH16 = c("En esta localidad" = 1,
                                        "En otra localidad de esta provincia" = 2,
                                        "En otra provincia (especificar)" = 3,
                                        "En un país limitrofe (especificar Brasil, Bolivia, Chile, Paraguay, Uruguay)" = 4,
                                        "En otro país (especificar)" = 5,
                                        "No había nacido" = 6,
                                        "Ns./Nr.." = 9),
                               CH16_COD = 'Especificar',
                               CH16_COD = c("En otra provincia" = 3,
                                            "En un paìs limítrofe" = 4,
                                            "En otro país." = 5),
                               NIVEL_ED = 'Nivel Educativo',
                               NIVEL_ED = c("Primaria incompleta (incluye educación especial)" = 1,
                                            "Primaria completa" = 2,
                                            "Secundaria incompleta" = 3,
                                            "Secundaria completa" = 4,
                                            "Superior universitaria incompleta" = 5,
                                            "Superior universitaria completa" = 6,
                                            "Sin instrucción" = 7,
                                            "Ns./Nr.." = 9),
                               ESTADO = 'Condición de actividad',
                               ESTADO = c("Entrevista individual no realizada (no respuesta al cuestionario individual)" = 0,
                                          "Ocupado" = 1,
                                          "Desocupado" = 2,
                                          "Inactivo" = 3,
                                          "Menor de 10 años." = 4),
                               CAT_OCUP = 'Categoría ocupacional',
                               CAT_OCUP = c("Patrón" = 1,
                                            "Cuenta propia" = 2,
                                            "Obrero o empleado" = 3,
                                            "Trabajador familiar sin remuneración" = 4,
                                            "Ns./Nr.." = 9),
                               CAT_INAC = 'Categoría de inactividad',
                               CAT_INAC = c("Jubilado / pensionado" = 1,
                                            "Rentista" = 2,
                                            "Estudiante" = 3,
                                            "Ama de casa" = 4,
                                            "Menor de 6 años" = 5,
                                            "Discapacitado" = 6,
                                            "Otros." = 7),
                               IMPUTA = 'Indica los casos que han sido imputados',
                               PP02C1 = '¿De Qué manera estuvo buscando trabajo? - Hizo contactos, entrevistas',
                               PP02C1 = c("Si" = 1,
                                          "No" = 2),
                               PP02C2 = '¿De Qué manera estuvo buscando trabajo? - Mandó curriculum, puso o contestó avisos',
                               PP02C2 = c("Si" = 1,
                                          "No" = 2),
                               PP02C3 = '¿De Qué manera estuvo buscando trabajo? - Se presentó en establecimientos',
                               PP02C3 = c("Si" = 1,
                                          "No" = 2),
                               PP02C4 = '¿De Qué manera estuvo buscando trabajo? - Hizo algo para ponerse por su cuenta',
                               PP02C4 = c("Si" = 1,
                                          "No" = 2),
                               PP02C5 = '¿De Qué manera estuvo buscando trabajo? - Puso carteles en negocios, preguntó en el barrio',
                               PP02C5 = c("Si" = 1,
                                          "No" = 2),
                               PP02C6 = '¿De Qué manera estuvo buscando trabajo? - Consultó a parientes, amigos',
                               PP02C6 = c("Si" = 1,
                                          "No" = 2),
                               PP02C7 = '¿De Qué manera estuvo buscando trabajo? - Se anotó en bolsas, listas, planes de empleo, agencias, contratistas o alguien le estpa buscando trabajo',
                               PP02C7 = c("Si" = 1,
                                          "No" = 2),
                               PP02C8 = '¿De Qué manera estuvo buscando trabajo? - Buscó trabajo de otra forma activa',
                               PP02C8 = c("Si" = 1,
                                          "No" = 2),
                               PP02E = 'Durante esos 30 días no busCó trabajo, porque...',
                               PP02E = c("está suspendido" = 1,
                                         "ya tiene trabajo asegurado" = 2,
                                         "se cansó de buscar tranajo" = 3,
                                         "hay poco trabajo en esta ?poca del año" = 4,
                                         "por otras razones." = 5),
                               PP02H = 'En los últimos 12 meses, ¿buscó trabajo en algún momento?',
                               PP02H = c("Si" = 1,
                                         "No" = 2),
                               PP02I = 'En los últimos 12 meses, ¿trabajó en algún momento?',
                               PP02I = c("Si" = 1,
                                         "No" = 2),
                               PP03C = 'La semana pasada, ¿tenía...',
                               PP03C = c("...un sólo empleo / ocupación / actividad?" = 1,
                                         "...más de un empleo / ocupación / actividad?." = 2),
                               PP03D = 'Cantidad de ocupaciones.',
                               PP3E_TOT = 'Total de horas que trabajó en la semana en la ocupación principal',
                               PP3F_TOT = 'Total de horas que trabajó en la semana en otras ocupaciones',
                               PP03G = 'La semana pasada, ¿quería trabajar más horas?',
                               PP03G = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP03H = 'Si hubiera conseguido más horas...',
                               PP03H = c("podÍa trabajarlas esta semana" = 1,
                                         "podÍa empezar a trabajarlas en dos semanas a más tardar" = 2,
                                         "no podÍa trabajar más horas" = 3,
                                         "Ns./Nr.." = 9),
                               PP03I = 'En los últimos 30 días, ¿buscó trabajar más horas?',
                               PP03I = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP03J = 'Aparte de este/os trabajo/s, ¿estuvo buscando algún empleo / ocupación / actividad?',
                               PP03J = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               INTENSI = 'INTENSI',
                               INTENSI = c("Subocupado por insuficiencia horaria" = 1,
                                           "Ocupado pleno" = 2,
                                           "Sobreocupado" = 3,
                                           "Ocupado que no trabajó en la semana" = 4,
                                           "Ns./Nr.." = 9),
                               PP04A = 'El negocio / empresa / institución / actividad en la que trabaja es (se refiere al que trabaja más horas semanales)...',
                               PP04A = c("...estatal" = 1,
                                         "...privada" = 2,
                                         "...de otro tipo" = 3,
                                         "Ns./Nr.." = 9),
                               PP04B_COD = '¿A qué se dedica o produce el negocio / empresa / institución?',
                               PP04B1 = 'Si presta servicio doméstico en hogares particulares',
                               PP04B1 = c("Casa de familia" = 1),
                               PP04B2 = '¿En cuántas casas trabaja?',
                               PP04B3_MES = '¿Cuánto tiempo hace que trabaja allí? - MES',
                               PP04B3_ANO = '¿Cuánto tiempo hace que trabaja allí? - AÑO',
                               PP04B3_DIA = '¿Cuánto tiempo hace que trabaja allí? - DÍAS',
                               PP04C = '¿Cuántas personas, incluído... trabajan allí en total?',
                               PP04C = c("1 persona" = 1,
                                         "2 personas" = 2,
                                         "3 personas" = 3,
                                         "4 personas" = 4,
                                         "5 personas" = 5,
                                         "6 a 10 personas" = 6,
                                         "11 a 25 personas" = 7,
                                         "26 a 40 personas" = 8,
                                         "de 41 a 100 personas" = 9,
                                         "de 101 a 200 personas" = 10,
                                         "de 201 a 500 personas" = 11,
                                         "más de 500 personas" = 12,
                                         "Ns./Nr." = 99),
                               PP04C99 = 'Tamaño del establecimiento',
                               PP04C99 = c("hasta 5" = 1,
                                           "de 6 a 40" = 2,
                                           "más de 40" = 3,
                                           "Ns./Nr.." = 9),
                               PP04D_COD =  'Código de ocupación',
                               PP04G = '¿Dónde realiza principalmente sus tareas?',
                               PP04G = c("En un local / oficina / establecimiento / neogocio / taller / chacra / finca" = 1,
                                         "En un puesto o kiosko fijo callejero" = 2,
                                         "En vehículos: bicicleta, moto, autos, barcos, botes (no incluye servicio de transporte)" = 3,
                                         "En vehículos para transporte de personas y mercaderías -aéreo, marítimo, terrestre-" = 4,
                                         "En obras en construcción, de infraestructura, minería o similares" = 5,
                                         "En esta vivienda (sin lugar exclusivo)" = 6,
                                         "En la vivienda del socio o del patrón" = 7,
                                         "En el domicilio / local de los clientes" = 8,
                                         "En la calle, espacios públicos, ambulante, de casa en casa, puesto móvil callejero" = 9,
                                         "En otro lugar (especificar)" = 10,
                                         "Ns./Nr." = 99),
                               PP05B2_MES = '¿Cuánto tiempo hace que trabaja en ese emPPleo en forma contínua? - MES',
                               PP05B2_ANO = '¿Cuánto tiempo hace que trabaja en ese emPPleo en forma contínua? - AÑO',
                               PP05B2_DIA = '¿Cuánto tiempo hace que trabaja en ese emPPleo en forma contínua? - DIA',
                               PP05C_1 = '¿En ese negocio / empresa / actividad, tiene... maquinarias / equipos?',
                               PP05C_1 = c("Propio (del negocio)" = 1,
                                           "Prestado / alquilado" = 2,
                                           "No tiene" = 3,
                                           "Ns./Nr.." = 9),
                               PP05C_2 = '¿En ese negocio / empresa / actividad, tiene... local (incluye kiosko, puesto fijo)?',
                               PP05C_2 = c("Propio (del negocio)" = 1,
                                           "Prestado / alquilado" = 2,
                                           "No tiene" = 3,
                                           "Ns./Nr.." = 9),
                               PP05C_3 = '¿En ese negocio / empresa / actividad, tiene... vehículo?',
                               PP05C_3 = c("Propio (del negocio)" = 1,
                                           "Prestado / alquilado" = 2,
                                           "No tiene" = 3,
                                           "Ns./Nr.." = 9),
                               PP05E = '¿Para la actividad del negocio, en los últimos 3 meses, tuvo que gastar en la compra de materias primas, productos, pagar servicios u otros gastos?',
                               PP05E = c("Si" = 1,
                                         "No" = 2,
                                         "Ns./Nr." = 9),
                               PP05F = '¿Ese negocio / empresa / actividad, trabaja habitualmente para...',
                               PP05H = '¿Durante cuánto tiempo ha estado trabajando en ese empleo de forma contínua? (con interrupciones laborales no mayores a 15 días)',
                               PP06A = '¿En ese negocio / empresa / actividad ¿tiene socios o familiares asociados?',
                               PP06A = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP06C = 'Monto de patrones y cuenta propia sin socios',
                               PP06D = 'Monto de patrones y cuenta propia con socios',
                               PP06E = '¿Ese negocio / empresa / actividad...',
                               PP06H = '¿Es una actividad familiar?',
                               PP07A = '¿Cuánto tiempo hace que está trabajando en ese empleo en forma contínua? (sin interrupcción de la relación laboral en la misma empresa / negocio / institución)',
                               PP07C = '¿Ese empleo tiene tiempo de finalización?',
                               PP07D = '¿Por cuánto tiempo es ese trabajo?',
                               PP07E = '¿Ese trabajo es...?',
                               PP07F1 = '¿En ese trabajo le dan... de comer gratis en el lugar de trabajo',
                               PP07F1 = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP07F2 = '¿En ese trabajo le dan... vivienda?',
                               PP07F2 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07F3 = '¿En ese trabajo le dan... algún producto o mercadería?',
                               PP07F3 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07F4 = '¿En ese trabajo le dan... aglún otro beneficio? (automóvil, teléfono celular, pasajes, etc.)',
                               PP07F4 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07F5 = '¿En ese trabajo le dan... no recibe ninguno?',
                               PP07F5 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07G1 = '¿En ese trabajo tiene... vacaciones pagas?',
                               PP07G1 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07G2 = '¿En ese trabajo tiene... aguinaldo?',
                               PP07G2 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07G3 = '¿En ese trabajo tiene... días pagos por enfermedad?',
                               PP07G3 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07G4 = '¿En ese trabajo tiene... obra social?',
                               PP07G4 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07G_59 = '¿En ese trabajo tiene... no tiene ninguno?',
                               PP07G_59 = c("Sí" = 1,
                                          "No" = 2,
                                          "Ns./Nr.." = 9),
                               PP07H = '¿Por ese trabajo tiene descuento jubilatorio?',
                               PP07H = c("Sí" = 1,
                                         "No" = 2),
                               PP07I = '¿Aporta por sí mismo a algún sistema jubilatorio?',
                               PP07I = c("Sí" = 1,
                                         "No" = 2),
                               PP07J = '¿El turno habitual de trabajo es...?',
                               PP07J = c("...de día" = 1,
                                         "...de noche" = 2,
                                         "...de otro tipo (rotativo, día y noche, guardias con franco." = 3),
                               PP07K = '¿Cuándo cobra...',
                               PP07K = c("...le dan recibo con sello / membrete / firma del empleador?" = 1,
                                         "...le dan un papel / recibo sin nada?" = 2,
                                         "...entrega una factura?" = 3,
                                         "...no le dan ni entrega nada?" = 4,
                                         "...no cobra, es trabajador sin pago / ad-honorem?." = 5),
                               PP08D1 = '¿Cuánto cobró por ese mes por esos conceptos? Monto total de sueldos/jornales, salario familiar, horas extras, otras bonificaciones habituales y tickets, vales o similares',
                               PP08D4 = 'Por el mes de...(mes)....¿cobró... Monto percibido en tickets.',
                               PP08F1 = '¿Cuánto cobró por ese mes de ..(mes)... Monto en pesos cobrado por Comisión por venta/producción.',
                               PP08F2 = '¿Cuánto cobró por ese mes de ..(mes)... Monto en pesos cobrado por Propinas.',
                               PP08J1 = '¿Cuánto cobró por ese mes de ..(mes)... Monto aguinaldo.',
                               PP08J2 = '¿Cuánto cobró por ese mes de ..(mes)... Monto otras bonificaciones no habituales.',
                               PP08J3 = '¿Cuánto cobró por ese mes de ..(mes)... Monto retroactivos.',
                               PP09A = 'SOLO OCUPADOS DE: CIUDAD DE BUENOS AIRES.  Partidos del GBA En su ocupación (o en la de más horas)¿trabaja....en ....',
                               PP09A = c("Ciudad de Buenos Aires" = 1,
                                         "Partidos del GBA" = 2,
                                         "Ambos" = 3,
                                         "En otro lugar." = 4),
                               PP09A_ESP = 'Especificar: contiene la descripción de otro lugar.',
                               PP09B = 'En su ocupación (o en la de más horas), trabaja... en esta ciudad?',
                               PP09B = c("Sí" = 1,
                                         "No" = 2),
                               PP09C = '¿Dónde trabaja...?',
                               PP09C = c("En otro lugar de esta provincia" = 1,
                                         "En otra provincia" = 2,
                                         "En otro país." = 3),
                               PP09C_ESP = 'Descripción de otro lugar (según pregunta PP09C).',
                               PP10A = '¿Cuánto hace que está buscando trabajo..?',
                               PP10A = c("Menos de 1 mes" = 1,
                                         "De 1 a 3 meses" = 2,
                                         "Más de 3 a 6 meses" = 3,
                                         "Más de 6 a 12 meses" = 4,
                                         "Más de 1 año." = 5),
                               PP10C = '¿Durante ese tiempo hizo algún trabajo / changa',
                               PP10C = c("Sí" = 1,
                                         "No" = 2),
                               PP10D = '¿Has trabajdo alguna vez?',
                               PP10D = c("Sí" = 1,
                                         "No" = 2),
                               PP10E = '¿Cuánto tiempo hace que terminó su último trabajo / changa?',
                               PP10E = c("Menos de 1 mes" = 1,
                                         "De 1 a 3 meses" = 2,
                                         "más de 3 a 6 meses" = 3,
                                         "Más de 6 a 12 meses" = 4,
                                         "Más de 1 a 3 años" = 5,
                                         "Más de 3 años." = 6),
                               PP11A = '¿El negocio / empresa / institución / actividad en la que trabaja era...?',
                               PP11A = c("Estatal" = 1,
                                         "Privado" = 2,
                                         "De otro tipo." = 3),
                               PP11B_COD = 'A qué se dedicaba ó que producía ese negocio/empresa/institución?',
                               PP11B1 = 'Si prestaba servicios domésticos en hogares particulares,',
                               PP11B1 = c("Casa de familia" = 1),
                               PP11B2_DIA = '¿Cuánto tiempo trabajó allí? - DIAS',
                               PP11B2_MES = '¿Cuánto tiempo trabajó allí? - MESES',
                               PP11B2_ANO = '¿Cuánto tiempo trabajó allí? - AÑOS',
                               PP11C = '¿Cuántas personas, inluído ... trabajan allí en total?',
                               PP11C = c("1 persona" = 1,
                                         "2 personas" = 2,
                                         "3 personas" = 3,
                                         "4 personas" = 4,
                                         "5 personas" = 5,
                                         "6 a 10 personas" = 6,
                                         "11 a 25 personas" = 7,
                                         "26 a 40 personas" = 8,
                                         "41 a 100 personas" = 9,
                                         "101 a 200 personas" = 10,
                                         "201 a 500 personas" = 11,
                                         "Más de 500 personas" = 12,
                                         "Ns./Nr." = 99),
                               PP11C99 = 'Ns./Nr. cuántas personas trabajan allí en total',
                               PP11C99 = c("Hasta 5 personas" = 1,
                                           "De 6 a 40 personas" = 2,
                                           "Más de 40 personas" = 3,
                                           "Ns./Nr.." = 9),
                               PP11D_COD = 'Cómo se llamaba la ocupación que tenía?',
                               PP11G_ANO = '¿Cuánto tiempo seguido estuvo trabajando en ese lugar? - AÑO',
                               PP11G_MES = '¿Cuánto tiempo seguido estuvo trabajando en ese lugar? - MES',
                               PP11G_DIA = '¿Cuánto tiempo seguido estuvo trabajando en ese lugar? - DIA',
                               PP11L = '¿Cuál fue la razón principal por la que dejó esa actividad?',
                               PP11L = c("falta de clientes/clientes que no pagan" = 1,
                                         "falta de capital/equipamiento" = 2,
                                         "trabajo estacional" = 3,
                                         "tenía gastos demasiado altos" = 4,
                                         "otras causas laborales (especificar)" = 5,
                                         "jubilación/retiro" = 6,
                                         "causas personales (matrimonio, embarazo cuidado de hijos o familiar, estudio, enfermedad)." = 7),
                               PP11L1 = '¿Ese trabajo era...',
                               PP11L1 = c("...una changa, trabajo transitorio, por tarea u obra, suplencia, etc?" = 1,
                                          "...un trabajo permanente, fijo, estable, de planta, etc.?" = 2,
                                          "Ns./Nr.." = 3),
                               PP11M = 'Ese trabajo era...',
                               PP11M = c("...un plan de empleo?" = 1,
                                         "...un período de prueba?" = 2,
                                         "...otro tipo de trabajo?" = 3),
                               PP11N = '¿En ese trabajo lehacían descuento jubilatorio?',
                               PP11N = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP11O = '¿Cuál fue la razón principal por la que dejó ese trabajo?',
                               PP11O = c("Despido / cierre (quiebre/venta/traslado de la empresa/reestructuración o recorte de personal/falta de ventas o clientes" = 1,
                                         "Por retiro voluntario del sector público" = 2,
                                         "Por jubilación" = 3,
                                         "Fin de tranajo temporario / estacional" = 4,
                                         "Le pagaban poco / no le pagaban" = 5,
                                         "Malas relaciones laborales / malas condiciones de trabajo (insalubre, cambios de horarios, etc.)" = 6,
                                         "Renuncia obligada / pactada" = 7,
                                         "Otras causas laborales" = 8,
                                         "Por razones personales (matrimonio, embarazo, cuidado de hijos o la familia, estudio, enfermedad)." = 9),
                               PP11P = '¿Cerró la empresa?',
                               PP11P = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP11Q =  '¿Fué la única persona que quedó sin trabajo?',
                               PP11Q = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               PP11R = '¿Le enviaron telegrama?',
                               PP11R = c("Sí" = 1,
                                         "No" = 2),
                               PP11S = '¿Le pagaron indemnización?',
                               PP11S = c("Sí" = 1,
                                         "No" = 2),
                               PP11T = '¿Está cobrando seguro de desempleo?',
                               PP11T = c("Sí" = 1,
                                         "No" = 2,
                                         "Ns./Nr.." = 9),
                               P21 = 'MONTO DE INGRESO DE LA OCUPACIÓN PRINCIPAL.',
                               DECOCUR = 'Nº de decil de ingreso de la ocupación principal del TOTAL EPH.',
                               IDECOCUR = 'Nº de decil de ingreso de la ocupación principal del INTERIOR EPH',
                               RDECOCUR = 'Nº de decil de ingreso de la ocupación principal de la REGION',
                               GDECOCUR = 'Nº de decil de ingreso de la ocupación principal del CONJUNTO DE AGLOMERADOS DE 500 MIL Y MAS HABITANTES',
                               PDECOCUR = 'Nº de decil de ingreso de la ocupación principal del CONJUNTO DE AGLOMERADOS DE MENOS DE 500 MIL HABITANTES',
                               ADECOCUR = 'Nº de decil de ingreso de la ocupación principal del AGLOMERADO.',
                               PONDIIO = 'Ponderador del ingreso de la ocupación principal.',
                               TOT_P12 = 'MONTO DE INGRESO DE OTRAS OCUPACIONES. (Incluye: ocupación secundaria, ocupación previa a la semana de referencia, deudas/retroactivos por ocupaciones anteriores al mes de referencia, etc).',
                               P47T = 'MONTO DE INGRESO TOTAL INDIVIDUAL(sumatoria ingresos laborales y no laborales).',
                               DECINDR = 'Nº de decil de ingreso total individual del TOTAL EPH.',
                               IDECINDR = 'Nº de decil de ingreso total individual del INTERIOR EPH.',
                               RDECINDR = 'Nº de decil de ingreso total individual de la REGION.',
                               GDECINDR = 'Nº de decil de ingreso total individual del CONJUNTO DE AGLOMERADOS DE 500 MIL Y MAS HABITANTES.',
                               PDECINDR = 'Nº de decil de ingreso total individual del CONJUNTO DE AGLOMERADOS DE MENOS DE 500 MIL HABITANTES.',
                               ADECINDR = 'Nº de decil de ingreso total individual del AGLOMERADO.',
                               PONDII = 'Ponderador para ingreso total individual.',
                               V2_M = 'Monto del ingreso por JUBILACION O PENSION.',
                               V3_M = 'Monto del ingreso por INDEMNIZACION POR DESPIDO.',
                               V4_M = 'Monto del ingreso por SEGURO DE DESEMPLEO.',
                               V5_M = 'Monto del ingreso por SUBSIDIO O AYUDA SOCIAL (EN DINERO) DEL GOBIERNO, IGLESIAS, ETC.',
                               V8_M = 'Monto del ingreso por ALQUILER (VIVIENDA , TERRENO, OFICINA, ETC.) DE SU PROPIEDAD.',
                               V9_M = 'Monto del ingreso por GANANCIAS DE ALGUN NEGOCIO EN EL QUE NO TRABAJÓ.',
                               V10_M = 'Monto del ingreso por INTERESES O RENTAS POR PLAZOS FIJOS/INVERSIONES.',
                               V11_M = 'Monto del ingreso por BECA DE ESTUDIO.',
                               V12_M = 'Monto del ingreso por CUOTAS DE ALIMENTOS O AYUDA EN DINERO DE PERSONAS QUE NO VIVEN EN EL HOGAR.',
                               V18_M = 'Monto del ingreso por OTROS INGRESOS EN EFECTIVO (LIMOSNAS, JUEGOS DE AZAR, ETC.).',
                               V19_AM = 'Monto del ingreso por TRABAJO DE MENORES DE 10 AÑOS.',
                               V21_M = 'Monto del ingreso por aguinaldo.',
                               T_VI = 'MONTO TOTAL DE INGRESOS NO LABORALES',
                               ITF = 'MONTO DEL INGRESO TOTAL FAMILIAR.',
                               DECIFR = 'Nº de decil de ingreso total familiar del TOTAL.',
                               IDECIFR = 'Nº de decil de ingreso total familiar del INTERIOR.',
                               RDECIFR = 'Nº de decil de ingreso total familiar de la REGION.',
                               GDECIFR = 'Nº de decil de ingreso total familiar del CONJUNTO DE AGLOMERADOS DE 500 MIL Y MAS HABITANTES.',
                               PDECIFR = 'Nº de decil de ingreso total familiar del CONJUNTO DE AGLOMERADOS DE MENOS DE 500 MIL HABITANTES.',
                               ADECIFR = 'Nº de decil de ingreso total familiar del AGLOMERADO (ver Anexo I).',
                               IPCF = 'MONTO DEL INGRESO PER CÁPITA FAMILIAR.',
                               DECCFR = 'Nº de decil de ingreso per cápita familiar del TOTAL EPH (ver Anexo I).',
                               IDECCFR = 'Nº de decil de ingreso per cápita familiar del  INTERIOR EPH (ver Anexo I).',
                               RDECCFR = 'Nº de decil de ingreso per cápita familiar de la REGION.',
                               GDECCFR = 'Nº de decil de ingreso per cápita familiar del CONJUNTO DE AGLOMERADOS DE 500 MIL Y MAS HABITANTES.',
                               PDECCFR = 'Nº de decil de ingreso per cápita familiar del CONJUNTO DE AGLOMERADOS DE MENOS DE 500 MIL HABITANTES.',
                               ADECCFR = 'Nº de decil de ingreso per cápita familiar del AGLOMERADO.',
                               PONDIH = 'Ponderador del ingreso total familiar y del ingreso per capita familiar, para hogares.')

